listen_port: 5354
metrics_port: 0
upstream:
  - "119.29.29.29:53"
cf_mrs_file4: "./cloudflare-v4.txt"
cf_mrs_file6: "./cloudflare-v6.txt"
aws_mrs_file64: "./aws.txt"
cf_mrs_cache: "./cloudflare.txt"
replace_cf_domain: "cc.cloudflare.182682.xyz" # 找一个好用的cf域名被替换
replace_aws_domain: "cc.cloudfront.182682.xyz"
cf_cache_time: 23h59m # 控制cf_mrs_cache文件在内存缓存的时间
replace_cache_time: "30m"
whitelist_file: "./whitelist.txt"
designated_domain: "./designated.txt" #指定域名走dns解析
log_level: "debug"
doh_port: 443
dot_port: 853
tls_cert_file: "./fullchain.pem"
tls_key_file: "./privkey.pem"
