listen_port: 5354
metrics_port: 0
upstream:
  - "10.0.0.1:1053"
cf_mrs_url4: "https://www.cloudflare-cn.com/ips-v4"
cf_mrs_url6: "https://www.cloudflare-cn.com/ips-v6"
cf_mrs_cache: "./cloudflare.txt"
replace_domain: "dd.com" # 找一个好用的cf域名被替换
cf_cache_time: 23h59m # 控制cf_mrs_cache文件在内存缓存的时间
replace_cache_time: "30m"
whitelist_file: "./whitelist.txt"
designated_domain: "./designated.txt" #指定域名走dns解析
log_level: "debug"
doh_port: 443
dot_port: 853
tls_cert_file: "./cert.pem"
tls_key_file: "./privkey.pem"