listen_port: 5354
metrics_port: 0

# 上游DNS服务器配置 - 直接使用DoH
cn_upstream:
  # - "https://doh.pub/dns-query"
  - "https://dns.alidns.com/dns-query"
not_cn_upstream:
  - "udp://10.0.0.1:1053"

doh:
  cn:
    enabled: true
    timeout: "5s"
    resolver: "119.29.29.29:53"
  not_cn:
    enabled: false
    timeout: "5s"
    resolver: "8.210.15.152:53"

# Cloudflare和AWS IP范围文件
cf_mrs_file4: "./data/cloudflare-v4.txt"
cf_mrs_file4_url: "https://www.cloudflare.com/ips-v4"
cf_mrs_file6: "./data/cloudflare-v6.txt"
cf_mrs_file6_url: "https://www.cloudflare.com/ips-v6"
aws_mrs_file64: "./data/aws.txt"
aws_mrs_file64_url: "https://ip-ranges.amazonaws.com/ip-ranges.json"
cf_mrs_cache: "./data/cloudflare.txt"

# 替换域名配置
replace_cf_domain: "cc.cloudflare.182682.xyz"
replace_aws_domain: "cc.cloudfront.182682.xyz"

# 缓存时间配置
cf_cache_time: 23h59m
replace_cache_time: "30m"

# 域名规则文件（统一到data目录）
whitelist_file: "./data/whitelist.txt"
designated_domain: "./data/designated.txt"

# 日志和监控
log_level: "info"

# TLS配置（DoH/DoT）
doh_port: 0
dot_port: 0
tls_cert_file: "./data/fullchain.pem"
tls_key_file: "./data/privkey.pem"

# Geosite配置
geosite_file: "./data/geosite.dat"
geosite_url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
geosite_refresh: 72h
geosite_group: "GEOLOCATION-CN"
