name: Go Multi-Platform Build and Release

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64]
        include:
          - os: windows
            ext: .exe
            archive: zip
          - os: linux
            ext: ""
            archive: tar.gz
          - os: darwin
            ext: ""
            archive: tar.gz

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Go 1.23.9
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.9'

      - name: Generate version
        id: version
        run: |
          SHORT_HASH=$(git rev-parse --short HEAD)
          DATE=$(date -u +'%Y%m%d%H%M%S')
          VERSION="v${DATE}-${SHORT_HASH}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          mkdir -p build
          echo "$VERSION" > build/version.txt

      - name: Build binary
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o build/dnsproxy${{ matrix.ext }} main.go
          cp config.yaml build/

      - name: Package binary and config
        run: |
          cd build
          PACKAGE=dnsproxy-${{ matrix.os }}-${{ matrix.arch }}-${{ env.VERSION }}
          if [ "${{ matrix.archive }}" = "zip" ]; then
            zip ../$PACKAGE.zip dnsproxy${{ matrix.ext }} config.yaml
          else
            tar -czvf ../$PACKAGE.tar.gz dnsproxy${{ matrix.ext }} config.yaml
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dnsproxy-${{ matrix.os }}-${{ matrix.arch }}-${{ env.VERSION }}
          path: |
            dnsproxy-${{ matrix.os }}-${{ matrix.arch }}-${{ env.VERSION }}.${{ matrix.archive }}
            build/version.txt
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      actions: read
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Find version file
        id: find_version
        run: |
          VERSION_FILE=$(find artifacts -name version.txt -type f | head -1)
          echo "VERSION=$(cat $VERSION_FILE)" >> $GITHUB_ENV
          echo "version_file=$VERSION_FILE" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}